export const EventNames = {
    PLACE_ORDER: 'PLACE_ORDER',
    UPDATE_ORDER: 'UPDATE_ORDER',
    CREATE_POLICY: 'CREATE_POLICY',
    REQUEST_POLICY: 'REQUEST_POLICY',
    ADD_USAGE_EVENT: 'ADD_USAGE_EVENT',
};